# Generated by Django 2.2 on 2021-11-12 11:54

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название принтера')),
                ('api_key', models.CharField(max_length=250, unique=True, verbose_name='Ключ доступа к API')),
                ('check_type', models.CharField(choices=[('client', 'client'), ('kitchen', 'kitchen')], max_length=50, verbose_name='Тип чека который печатает принтер')),
                ('point_id', models.IntegerField(verbose_name='Точка к которой привязан принтер')),
            ],
            options={
                'verbose_name': 'Принтер',
                'verbose_name_plural': 'Принтеры',
            },
        ),
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defined_type', models.CharField(choices=[('client', 'client'), ('kitchen', 'kitchen')], max_length=50, verbose_name='Тип чека')),
                ('order', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='Информация о заказе')),
                ('status', models.CharField(choices=[('new', 'new'), ('rendered', 'rendered'), ('printed', 'printed')], default='new', max_length=50, verbose_name='Статус чека')),
                ('pdf_file', models.FileField(blank=True, max_length=5000, null=True, upload_to='', verbose_name='Ссылка на созданный PDF-файл')),
                ('printer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='api.Printer', verbose_name='Принтер')),
            ],
            options={
                'verbose_name': 'Чек',
                'verbose_name_plural': 'Чеки',
            },
        ),
    ]
