# Generated by Django 2.2 on 2021-10-27 21:46

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='printer',
            options={'verbose_name': 'Принтер', 'verbose_name_plural': 'Принтеры'},
        ),
        migrations.AddField(
            model_name='check',
            name='order',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'address': 'г. Уфа, ул. Ленина, д. 42', 'client': {'name': 'Иван', 'phone': 9173332222}, 'id': 123456, 'items': [{'name': 'Вкусная пицца', 'quantity': 2, 'unit_price': 250}, {'name': 'Не менее вкусные роллы', 'quantity': 1, 'unit_price': 280}], 'point_id': 1, 'price': 780}, verbose_name='Информация о заказе'),
            preserve_default=False,
        ),
    ]
