# Generated by Django 3.2.8 on 2021-10-28 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211027_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Ссылка на созданный PDF-файл'),
        ),
    ]
