# Generated by Django 3.2.8 on 2021-10-29 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_check_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='pdf_file',
            field=models.FileField(blank=True, max_length=5000, null=True, upload_to='', verbose_name='Ссылка на созданный PDF-файл'),
        ),
    ]
